name: Publish .NET 8 NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: [ self-hosted ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Specifically for .NET 8

      - name: Set environment variables
        run: |
          echo "HOME=$HOME" >> $GITHUB_ENV
          echo "DOTNET_CLI_HOME=$HOME" >> $GITHUB_ENV

      - name: Display environment variables
        run: |
          echo "HOME: $HOME"
          echo "DOTNET_CLI_HOME: $DOTNET_CLI_HOME"
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release -o nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg