name: Docker Build and Publish NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: [ self-hosted ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t mbs-contract:latest -f MBS-CONTRACT.SHARE/Dockerfile .
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Copy NuGet package from Docker container
        run: |
          docker create --name temp mbs-contract:latest
          docker cp temp:/app/nupkg ./nupkg
          docker rm temp

      - name: Push to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg